/**
 * Demo API
 * Demo API for swagger code generation
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface TodoModel { 
    id?: number;
    title?: string;
    description?: string;
    isDone?: boolean;
}